[package]
name = "orgorg"
version = "0.2.0"
edition = "2024"
license = "MIT"
description = "no_std compatible Cave Story Organya Music Player"
categories = ["no-std", "no-std::no-alloc", "multimedia::audio"]
keywords = ["no_std", "audio", "music"]
repository = "https://github.com/kpqi5858/orgorg"

[features]
fma = []
fma-nightly = []
f32smp = []

[dependencies]
wide = { version = "1.1.1", optional = true }
